# Generated by Django 5.0.2 on 2024-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='investors/')),
            ],
        ),
        migrations.CreateModel(
            name='investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invName', models.CharField(max_length=50)),
                ('invDonationTime', models.CharField(max_length=50)),
                ('invMoney', models.CharField(max_length=10)),
                ('invPurpose', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='investors/')),
            ],
        ),
        migrations.CreateModel(
            name='schoolnums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfSchool', models.IntegerField()),
                ('states', models.IntegerField()),
            ],
        ),
    ]
