# Generated by Django 5.0.2 on 2024-04-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnums',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='HomeImages/'),
        ),
    ]
