# Generated by Django 5.0.2 on 2024-04-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_schoolnums_video_alter_homepageimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolnums',
            old_name='states',
            new_name='numberOfStates',
        ),
    ]
