# Generated by Django 5.0.2 on 2024-04-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_states_schoolnums_numberofstates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='invDonationTime',
            field=models.DateTimeField(null=True),
        ),
    ]
