# Generated by Django 5.0.2 on 2024-04-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textarea', models.CharField(max_length=1000)),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textarea', models.CharField(max_length=1000)),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField(null=True)),
                ('heading', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='teamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Member', 'Member'), ('Admin', 'Admin'), ('Volunteer', 'Volunteer')], max_length=100)),
                ('sinceJoined', models.DateTimeField(null=True)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
    ]
