# Generated by Django 5.0.2 on 2024-04-13 19:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='textarea',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='textarea',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
