# Generated by Django 5.0.2 on 2024-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_alter_aboutus_textarea_alter_blog_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member'), ('Volunteer', 'Volunteer')], max_length=100),
        ),
    ]
